### ISSUE TITLE
El método PlotEvolution(pred=pred, cumm=True, right_axis=False) de la clase yam no funciona correctamente.

### ISSUE THREAD

**Issue by crissthiandi** [victoriaepidemics/Victoria#4]
El método usado en eyam.PlotEvolution(pred=pred, cumm=True, right_axis=False) no lo encontré en las definición de la clase eyam, sospecho debe estar solo en el archivo victoriaepi-0.0.1.tar.gz porque ya instalado el paquete si se tiene una definición de este método.

Por otro lado hay un error al ejecutar  [AnalyzeEyam.py](victoriaepi/examples/AnalyzeEyam.py),
![image](https://user-images.githubusercontent.com/36548949/107684385-5564cc80-6c68-11eb-9433-c67010363fbf.png)
el error se encuentra en un sub metodo llamado **PlotEvolution_fm**

**Comment by fou-foo** [comment]
Al intentar recrear al ejemplo del README me pasó el mismo error, he detectado que el issue esta en la clase `mcmc` en el método **PlotEvolution_fm**, en un ambiente windows.

**Comment by crissthiandi** [comment]
Sip en esa clase lo encontré igual, pero no lo solucione, en parte porque ese error no afectaba con la obtención de los raw (pronósticos) para trabajar el modelo AMA. Aunque estaría padre resolverlo cuando se tenga la mayor cantidad de conocimiento de como el modelo fue programado.

**Comment by victoriaepidemics** [comment]
El error se daba a un método del modulo de matplotlibs que en ciertos casos creaba fechas negativas, el bug ha sido tratado de diferente forma para que se corra correctamente el ejemplo de EYAM.

**Comment by fou-foo** [comment]
Funciona @crissthiandi  :)

**Comment by crissthiandi** [comment]
Excelente, lo probare en este fin :3
Saludos @fou-foo y gracias @victoriaepidemics
